// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: rpc/proto/task.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`  // 命令
	Timeout       int32                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"` // 任务执行超时时间(秒)
	Id            int64                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`           // 执行任务唯一ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_rpc_proto_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *TaskRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *TaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        *string                `protobuf:"bytes,1,opt,name=output,proto3,oneof" json:"output,omitempty"`                            // 标准输出(stdout)
	Stderr        *string                `protobuf:"bytes,5,opt,name=stderr,proto3,oneof" json:"stderr,omitempty"`                            // 标准错误输出(stderr)
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`                              // 执行错误信息
	ExitCode      *int32                 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`       // 退出码
	StartTime     *int64                 `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`    // 开始执行时间戳(毫秒)
	EndTime       *int64                 `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3,oneof" json:"end_time,omitempty"`          // 结束执行时间戳(毫秒)
	DurationMs    *int64                 `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3,oneof" json:"duration_ms,omitempty"` // 执行耗时(毫秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_rpc_proto_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_rpc_proto_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetOutput() string {
	if x != nil && x.Output != nil {
		return *x.Output
	}
	return ""
}

func (x *TaskResponse) GetStderr() string {
	if x != nil && x.Stderr != nil {
		return *x.Stderr
	}
	return ""
}

func (x *TaskResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *TaskResponse) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *TaskResponse) GetStartTime() int64 {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return 0
}

func (x *TaskResponse) GetEndTime() int64 {
	if x != nil && x.EndTime != nil {
		return *x.EndTime
	}
	return 0
}

func (x *TaskResponse) GetDurationMs() int64 {
	if x != nil && x.DurationMs != nil {
		return *x.DurationMs
	}
	return 0
}

var File_rpc_proto_task_proto protoreflect.FileDescriptor

const file_rpc_proto_task_proto_rawDesc = "" +
	"\n" +
	"\x14rpc/proto/task.proto\x12\x03rpc\"Q\n" +
	"\vTaskRequest\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x05R\atimeout\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x03R\x02id\"\xc9\x02\n" +
	"\fTaskResponse\x12\x1b\n" +
	"\x06output\x18\x01 \x01(\tH\x00R\x06output\x88\x01\x01\x12\x1b\n" +
	"\x06stderr\x18\x05 \x01(\tH\x01R\x06stderr\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x02R\x05error\x88\x01\x01\x12 \n" +
	"\texit_code\x18\x03 \x01(\x05H\x03R\bexitCode\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03H\x04R\tstartTime\x88\x01\x01\x12\x1e\n" +
	"\bend_time\x18\a \x01(\x03H\x05R\aendTime\x88\x01\x01\x12$\n" +
	"\vduration_ms\x18\x04 \x01(\x03H\x06R\n" +
	"durationMs\x88\x01\x01B\t\n" +
	"\a_outputB\t\n" +
	"\a_stderrB\b\n" +
	"\x06_errorB\f\n" +
	"\n" +
	"_exit_codeB\r\n" +
	"\v_start_timeB\v\n" +
	"\t_end_timeB\x0e\n" +
	"\f_duration_ms24\n" +
	"\x04Task\x12,\n" +
	"\x03Run\x12\x10.rpc.TaskRequest\x1a\x11.rpc.TaskResponse\"\x00B.Z,github.com/lynnyq/hdp-disk-inspect/rpc/protob\x06proto3"

var (
	file_rpc_proto_task_proto_rawDescOnce sync.Once
	file_rpc_proto_task_proto_rawDescData []byte
)

func file_rpc_proto_task_proto_rawDescGZIP() []byte {
	file_rpc_proto_task_proto_rawDescOnce.Do(func() {
		file_rpc_proto_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_proto_task_proto_rawDesc), len(file_rpc_proto_task_proto_rawDesc)))
	})
	return file_rpc_proto_task_proto_rawDescData
}

var file_rpc_proto_task_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_proto_task_proto_goTypes = []any{
	(*TaskRequest)(nil),  // 0: rpc.TaskRequest
	(*TaskResponse)(nil), // 1: rpc.TaskResponse
}
var file_rpc_proto_task_proto_depIdxs = []int32{
	0, // 0: rpc.Task.Run:input_type -> rpc.TaskRequest
	1, // 1: rpc.Task.Run:output_type -> rpc.TaskResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_proto_task_proto_init() }
func file_rpc_proto_task_proto_init() {
	if File_rpc_proto_task_proto != nil {
		return
	}
	file_rpc_proto_task_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_task_proto_rawDesc), len(file_rpc_proto_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_task_proto_goTypes,
		DependencyIndexes: file_rpc_proto_task_proto_depIdxs,
		MessageInfos:      file_rpc_proto_task_proto_msgTypes,
	}.Build()
	File_rpc_proto_task_proto = out.File
	file_rpc_proto_task_proto_goTypes = nil
	file_rpc_proto_task_proto_depIdxs = nil
}
